AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Creates the cloud infrastructure to test RDS database failover

Parameters:
  Program:
    Type: String
    Default: Chaos
    Description: The name of the implementation program

  TemplatesBucketSuffix:
    Type: String
    Description: What is the suffix of the S3 buckets containing cf-templates?
    Default: cf-templates

  VpcCidr:
    Type: String
    Default: "10.1.0.0/16"
    Description: What is the cidr block for the master VPC?
    AllowedPattern: ^([0-9]{1,3}\.){3}([0-9]{1,3})\/[0-9]{1,2}$

  NumberOfAZs:
    Type: Number
    Default: 2
    Description: How many AZs do you want to use (1-3) ?
    AllowedValues:
      - 1
      - 2
      - 3

  DbInstanceType:
    Type: String
    Default: "db.t3.medium"

  DatabaseUsername:
    Type: String
    Default: "dbuser"

  DatabasePassword:
    Type: String
    Default: "changeme"

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${AWS::AccountId}-${TemplatesBucketSuffix}.s3.amazonaws.com/networking/vpc.yaml"
      Parameters:
        Name: !Ref Program
        VpcCidr: !Ref VpcCidr
        NumberOfAZs: !Ref NumberOfAZs
      TimeoutInMinutes: 10

  DBSubnetGroup:
    Properties:
      DBSubnetGroupDescription: description
      SubnetIds: !Split [ ',', !GetAtt VPC.Outputs.PublicSubnetIds]
      Tags:
        - Key: "Program"
          Value: !Ref Program
    Type: "AWS::RDS::DBSubnetGroup"

  RDSCluster: 
    Properties: 
      DBClusterParameterGroupName: 
        Ref: RDSDBClusterParameterGroup
      DBSubnetGroupName: 
        Ref: DBSubnetGroup
      Engine: aurora
      EngineMode: provisioned
      MasterUserPassword: 
        Ref: DatabasePassword
      MasterUsername: 
        Ref: DatabaseUsername
    Type: "AWS::RDS::DBCluster"
  RDSDBClusterParameterGroup: 
    Properties: 
      Description: "CloudFormation Sample Aurora Cluster Parameter Group"
      Family: aurora-mysql8.0
      Parameters: 
        time_zone: US/Eastern
    Type: "AWS::RDS::DBClusterParameterGroup"
  RDSDBInstance1: 
    Properties: 
      DBClusterIdentifier: 
        Ref: RDSCluster
      DBInstanceClass: !Ref DbInstanceType
      DBParameterGroupName: 
        Ref: RDSDBParameterGroup
      DBSubnetGroupName: 
        Ref: DBSubnetGroup
      Engine: aurora
      PubliclyAccessible: "true"
    Type: "AWS::RDS::DBInstance"
  RDSDBInstance2: 
    Properties: 
      DBClusterIdentifier: 
        Ref: RDSCluster
      DBInstanceClass: !Ref DbInstanceType
      DBParameterGroupName: 
        Ref: RDSDBParameterGroup
      DBSubnetGroupName: 
        Ref: DBSubnetGroup
      Engine: aurora
      PubliclyAccessible: "true"
    Type: "AWS::RDS::DBInstance"
  RDSDBParameterGroup:
    Type: 'AWS::RDS::DBParameterGroup'
    Properties:
      Description: CloudFormation Sample Aurora Parameter Group
      Family: aurora-mysql8.0
      Parameters:
        sql_mode: IGNORE_SPACE
        max_allowed_packet: 1024
        innodb_buffer_pool_size: '{DBInstanceClassMemory*3/4}'
